version: '3.9'

services:
  db:
    image: postgres:15
    container_name: dispatcher_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  minio:
    image: minio/minio
    container_name: dispatcher_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  minio-init:
    build:
      context: ./minio-init
    depends_on:
      - minio
    restart: "no"

volumes:
  pgdata:
  minio-data:
